name = "linquiz-api"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "COOLDOWN_KV"
id = "53865c1abe754d3faf61c3492b4060cd"

[[d1_databases]]
binding = "DB"
database_name = "lunquiz-db"
database_id = "ab80b00a-bdb1-41b6-b998-f0d7e93d6334"
